name: "Build"
on: [workflow_dispatch,push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4.2.1
        with: 
          go-version: 1.24.2
      #- uses: cda-tum/setup-z3@v1.6.5
      - uses: pavpanchekha/setup-z3@v1.3
      - name: List z3 contents
        run: ls ${{env.LIBRARY_PATH}}
      - name: (windows only) set env vars another way
        if: matrix.os == "windows-latest"
        run: set CGO_CFLAGS=${{env.CPATH}}
      - run: go build .
        env: 
          CGO_LDFLAGS: -L${{env.LIBRARY_PATH}}
          CGO_CFLAGS: -I${{env.CPATH}}
          
