name: "Build"
on: [workflow_dispatch,push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4.2.1
        with: 
          go-version: 1.24.2
      #- uses: cda-tum/setup-z3@v1.6.5
      - uses: pavpanchekha/setup-z3@v1.3
      - run: echo ${{env.CPATH}}
      - run: echo ${{env.LIBRARY_PATH}}
      - run: go build .
