name: "Test"
on: [workflow_dispatch,push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4.2.1
      - uses: cda-tum/setup-z3@v1.6.5
      - run: go build .
